name: nyc_taxi
version: "0.1.0"
profile: nyc_taxi

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
clean-targets: ["target", "dbt_packages"]

models:
  nyc_taxi:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      core:
        +materialized: table
      reporting:
        +materialized: table

seeds:
  nyc_taxi:
    +schema: seeds
    taxi_zones:
      +column_types:
        location_id: INT64
    vendors:
      +column_types:
        vendor_id: INT64
        in_current_dictionary: BOOLEAN
    rate_codes:
      +column_types:
        ratecode_id: INT64
    payment_types:
      +column_types:
        payment_type: INT64
